### PR TITLE
Pull Request for Code Review

### PR DESCRIPTION
**Pull request by fredericomba**
This is a pull request created for a code review and invoking the automatic CSS linter.

### CODE REVIEW

**Comment by shloch** [comment]
### Pull request under review by SHEY LOUIS

**Comment by shloch** [comment]
### Changes Required 🤓
Hi @frederico-miranda &&  @mikenath223   👋,

You've done a great job setting up this project so far. 😄

Please i need you to bring minor modifications
- Put the live demo link on the README file (you can use `https://raw.githack.com/` to generate demo link)
- Your HTML is almost entirely valid, but ONE (01) more error left, please fix that (use `https://validator.w3.org/#validate_by_input` for validation)
- "THE NEW YORK TIMES" logo on the top, **SHOULD BE A LINK**
- **FOOTER** too  should have a fixed position (it sticks to the bottom part of the screen). Just as you did for nav bar

Your design looks good . 

**### Do the minor changes and file for a re-view, and we'll be good** 

Happy coding

**Comment by mikenath223** [comment]
I have filed for a review.
Still waiting

**Comment by frederico-miranda** [comment]
The link for the live preview of this is here:
https://raw.githack.com/mikenath223/Positioning-and-Floating-Elements/feature-branch/index.html

The footer should have a fixed position, and I'm working on that.

**Comment by shloch** [comment]
You'll have your review by end of the day, don't worry....move to next project while waiting :) 😄😄

**Comment by shloch** [comment]
**### Hi @frederico-miranda && @mikenath223 👋**
Great Job with the corrections 

Your live demo link still not working
here it is i generated using https://raw.githack.com ---> [`https://raw.githack.com/mikenath223/Positioning-and-Floating-Elements/feature-branch/index.html#`](url)

I count on your to update your README before merging .

THIS PROJECT IS CONSIDERED VALID 👏 👏 

Happy coding

**Comment by mikenath223** [comment]
Sure we will.
Thanks

**Comment by shloch** [comment]
### Hello @mikenath223 ,

Please for all remaining projects (of the  **_"HTML + CSS_**" section), do use the **GITHUB FLOW** (details about it here --> `https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/`

You used the **GIT FLOW** for this project, which is reserved for Ruby section and above

It's very essential, so that your entire project don't get rejected

Happy coding

**Pull request merged**
